// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfyzapmncnwhqiihvddh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeXphcG1uY253aHFpaWh2ZGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzQ3ODIsImV4cCI6MjA2NDgxMDc4Mn0.fZe_HCsU467Sp6-O1PNnd7X3NMWYsTk4GW2rRhN5S1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);